### ISSUE TITLE
Arc border not curving properly

### ISSUE THREAD

**Issue by fahad-mirza** [asjadnaqvi/stata-circlebar#11]
The plot is not drawing properly as you can see in the image below the outer line of the arc is not curving properly. 

The data initially has 14 categories from which I choose top 3 most selected categories. I do that by marking the top 3 categories by group and then assigning 0 to the rest. After that, I drop all other categories that dont get used. 

Please let me know if sharing the sample data will help debug this. 

code used:
`circlebar total, by(time_catn) stack(activity) scheme(white_tableau) nocirclab text(0 0 "Time Use" "{bf:Top 3 activities}" "(by time category)",  size(2.5)) radmin(4) lc(black) circc(gs13) ra(10000)`

Image:
![time_use](https://github.com/asjadnaqvi/stata-circlebar/assets/73574837/253308a7-8f81-48d4-b67e-237e89cf3468)

**Comment by asjadnaqvi** [comment]
Thanks Fahad! This is a known issue. The command cannot currently handle different categories for each group and it will mess up the labels. I need to expand the command to include these. If you draw with the complete dataset, it should hopefully give you the correct color assignment.

I will add an error check to make sure the drawn categories are comparable. 

Also should fix the curve that is not drawn properly.
