### ISSUE TITLE
Legend not plotting correctly when using stack() and circtop

### ISSUE THREAD

**Issue by sktanamas** [asjadnaqvi/stata-circlebar#13]
Hi, 
Thank you for developing this great package. I noticed a bug where if circtop is used with stack() then the legend incorrectly uses the reference circles as a symbol for the first label, and the symbol for the first label for the second label.

The first figure below (**without** circtop) has the correct legend (blue = compliant, orange = non-compliant)
![Figure1](https://github.com/asjadnaqvi/stata-circlebar/assets/107591333/99ab456b-96f7-4596-b192-fb1ee7cb4f06)

The second figure below (**with** circtop) incorrectly labels the blue shaded area as 'non-compliant' and the grey reference line is labelled as 'compliant'
![Figure2](https://github.com/asjadnaqvi/stata-circlebar/assets/107591333/b0e712f6-3a73-4501-a4ec-decf308c14bf)

Please advise if there is something I'm doing wrong. My stata code is below

// Without 'circtop'
`circlebar cat, by(procedure) stack(choice) 	///
	palette(tab Color Blind, n(6)) 	///
	gap(2)   ///
	circ(5) circc(gs13) labgap(10) rotatelab labs(2.4) 	///
	circlabf(%6.0fc) circlabc() circlabs(2.4)`

// With 'circtop'
`circlebar cat, by(procedure) stack(choice) 	///
	palette(tab Color Blind, n(6)) 	///
	gap(2) circtop   ///
	circ(5) circc(gs13) labgap(10) rotatelab labs(2.4) 	///
	circlabf(%6.0fc) circlabc() circlabs(2.4)`

**Comment by asjadnaqvi** [comment]
Hello! I cannot reproduce the error. 

Using the data I provided with the examples if I run:

```
circlebar deathspm if inlist(continent, "Africa", "Asia" ), by(month) stack(continent) circtop
```

I get the correct legend assignment

![test1](https://github.com/asjadnaqvi/stata-circlebar/assets/38498046/11b2a2fe-5af1-4fc0-9d42-22b15453ee2a)

Can you:
1. Check if you have the latest version `which circlebar` should say v1.2. If not then update it: `ssc install circlebar, replace`.
2. If the error still persists, send some data that reproduces the error.

Thank you!

**Comment by sktanamas** [comment]
Hi,

Thank you for responding so promptly.
I checked the version and I do have v1.2 dated 23 Mar 2023.

Please see sample data attached, and the figure that I get when using the following code `circlebar round , by(procedure) stack(timing_cat) circtop`
[test_circbar.xlsx](https://github.com/asjadnaqvi/stata-circlebar/files/12709881/test_circbar.xlsx)
![testGraph](https://github.com/asjadnaqvi/stata-circlebar/assets/107591333/a5c61609-2b90-4b8f-bb51-b0fa466dc02d)
