### ISSUE TITLE
The current Stata update

### ISSUE THREAD

**Issue by ericmelse** [asjadnaqvi/stata-circlebar#14]
Dear Asjad, not an issue but a note (in case that you are not aware) that the current Stata update ( "04 Oct 2023") includes:

graph twoway now supports aspect ratios that provide common units in the x and y dimensions. 
Adding option aspectratio(1, units) creates a graph where one unit in the x dimension and one unit in the y dimension each take up the same distance on the plot. 
This is useful for plotting things such as latitude against longitude, which have common scaling of their units.

I suppose that this is relevant to `circlebar`.

Best,
Eric

**Comment by asjadnaqvi** [comment]
Dear Eric,

Thank you and it is very useful to know! I will check it out especially how important it is for backward compabitability.
