### ISSUE TITLE
Error of option

### ISSUE THREAD

**Issue by kienns097** [asjadnaqvi/stata-circlebar#9]
Dear Prof. Asjadnaqvi,

I wish you all the bests,
I tried to learn the circlebar from your great guidance. However, I got the issue of 
"option - not allowed
r(198);"

Would you please help me check this?
Thank you and kind regards,
Son kien (Ph.D. student economics).
![error](https://user-images.githubusercontent.com/109412765/217561536-73cee21f-cb6b-444d-8b7d-82c03d38dd59.png)

**Comment by asjadnaqvi** [comment]
This has been fixed in the current version on GitHub.

**Comment by kienns097** [comment]
Dear Prof Asjadnaqvi,

It is worked now. Thank you in advance for your advice,
It was great to know (and learn from) you. These tools are really fantastics. 

I wish you all the bests,
Many thanks and kind regards,
Son kien.
